# Generated by Django 4.2.5 on 2023-11-07 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('campeonato_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.IntegerField(primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Colete',
            fields=[
                ('colete_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cor', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EspacoEsportivo',
            fields=[
                ('espaco_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_espaco', models.CharField(max_length=255)),
                ('tamanho', models.CharField(max_length=255)),
                ('capacidade', models.IntegerField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('locacao_id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_locacao', models.DateField()),
                ('valor', models.IntegerField()),
                ('foi_pago', models.BooleanField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('partida_id', models.IntegerField(primary_key=True, serialize=False)),
                ('duracao_horas', models.IntegerField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.campeonato')),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.espacoesportivo')),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.locacao')),
            ],
        ),
        migrations.CreateModel(
            name='Narracao',
            fields=[
                ('narracao_id', models.IntegerField(primary_key=True, serialize=False)),
                ('narradores', models.CharField(max_length=255)),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.locacao')),
            ],
        ),
        migrations.CreateModel(
            name='LocacaoColete',
            fields=[
                ('locacao_colete_id', models.IntegerField(primary_key=True, serialize=False)),
                ('colete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.colete')),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.locacao')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cnpj', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=255)),
                ('bairro_endereco', models.CharField(max_length=255)),
                ('numero_endereco', models.CharField(max_length=255)),
                ('rua_endereco', models.CharField(max_length=255)),
                ('horario_comercial', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.espacoesportivo')),
            ],
        ),
        migrations.AddField(
            model_name='colete',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa'),
        ),
    ]
