### FindAll
GET http://localhost:3000/alugueis-coletes HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsIm5hbWUiOiJFZHVhcmFzZGFzZGZmZG8iLCJwZXJmaWwiOiJhZGFzZGZtaW4iLCJpYXQiOjE2OTk3NDcwMzAsImV4cCI6MTY5OTgzMzQzMH0.YMhhfyuSEUxYWKFsUUjoPV-4-movEacQRqYleu6dS7M

### FindOne
GET http://localhost:3000/alugueis-coletes/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsIm5hbWUiOiJFZHVhcmFzZGFzZGZmZG8iLCJwZXJmaWwiOiJhZGFzZGZtaW4iLCJpYXQiOjE2OTk3NDcwMzAsImV4cCI6MTY5OTgzMzQzMH0.YMhhfyuSEUxYWKFsUUjoPV-4-movEacQRqYleu6dS7M

### Create
POST http://localhost:3000/alugueis-coletes HTTP/1.1
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsIm5hbWUiOiJFZHVhcmFzZGFzZGZmZG8iLCJwZXJmaWwiOiJhZGFzZGZtaW4iLCJpYXQiOjE2OTk3NDcwMzAsImV4cCI6MTY5OTgzMzQzMH0.YMhhfyuSEUxYWKFsUUjoPV-4-movEacQRqYleu6dS7M

{
    "coleteId": 1,
    "locacaoId": 2,
    "data_inicio_locacao": "2023-11-19T21:49:58.543Z",
    "data_final_locacao": "2023-11-20T22:49:58.543Z"
}

### Update
PUT http://localhost:3000/alugueis-coletes/1 HTTP/1.1
Content-Type: application/json

{
    "data_inicio_locacao": "2023-11-11T21:49:58.543Z",
    "data_final_locacao": "2023-11-11T23:49:58.543Z"
}

### Remove
DELETE http://localhost:3000/alugueis-coletes/6 HTTP/1.1