### FindAll
GET http://localhost:3000/coletes HTTP/1.1

### FindOne
GET http://localhost:3000/coletes/1 HTTP/1.1

### Create
POST http://localhost:3000/coletes HTTP/1.1
Content-Type:  application/json

{
    "cor": "vermelho",
    "valor_quantidade": 10,
    "empresa_id": 2
}

### Update
PATCH http://localhost:3000/coletes/1 HTTP/1.1
Content-Type: application/json

{
    "cor": "vermelho",
    "valor_quantidade": 10,
    "empresa_id": 2
}

### Remove
DELETE http://localhost:3000/coletes/1 HTTP/1.1