### FindAll
GET http://localhost:3000/empresas HTTP/1.1

### FindOne
GET http://localhost:3000/empresas/1 HTTP/1.1

### Create
POST http://localhost:3000/empresas HTTP/1.1
Content-Type:  application/json

{
    "cnpj": "5555555",
    "cep": "13585458",
    "bairro_endereco": "Bairro Daqui",
    "numero_endereco": "858",
    "rua_endereco": "Rua mesmo",
    "horario_comercial_inicio": "08:00",
    "horario_comercial_final": "18:00",
    "nome": "Onzemais"
}

### Update
PATCH http://localhost:3000/empresas/id HTTP/1.1
Content-Type: application/json

{
    "cnpj": "",
    "cep": "",
    "bairro_endereco": "",
    "numero_endereco": "",
    "rua_endereco": "",
    "horario_comercial_inicio": "",
    "horario_comercial_final": "",
    "nome": ""
}

### Remove
DELETE http://localhost:3000/empresas/1 HTTP/1.1