### FindAll
GET http://localhost:3000/partidas HTTP/1.1

### FindOne
GET http://localhost:3000/partidas/1 HTTP/1.1

### Create
POST http://localhost:3000/partidas HTTP/1.1
Content-Type:  application/json

{
    "data_inicio_locacao": "2023-11-11T21:49:58.543Z",
    "data_final_locacao": "2023-11-11T23:49:58.543Z",
    "locacaoId": 2,
    "espacoId": 2,
    "campeonatoId": 1
}

### Update
PATCH http://localhost:3000/partidas/1 HTTP/1.1
Content-Type: application/json

{
    "data_inicio_locacao": "2023-11-11T21:49:58.543Z",
    "data_final_locacao": "2023-11-11T22:49:58.543Z"
}

### Remove
DELETE http://localhost:3000/partidas/1 HTTP/1.1